# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kSRNepo9Xj5BRDUTj4q5CKGMveu4dqDY
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

def load_data(file_path):
    return pd.read_csv(file_path)

def preprocess_data(df):
    X = df.copy()
    numeric_features = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
    numeric_transformer = Pipeline([
        ("imputer", SimpleImputer(strategy="mean")),
        ("scaler", StandardScaler())
    ])
    preprocessor = ColumnTransformer([
        ("num", numeric_transformer, numeric_features)
    ])
    X_processed = preprocessor.fit_transform(X)
    return X_processed

def add_features(df):
    df["Temp_CO2_ratio"] = df["Temperature"] / (df["CO2"] + 1e-5)
    return df

def validate_data(df):
    required = ["Temperature", "Humidity", "Light", "CO2", "HumidityRatio"]
    for col in required:
        if col not in df.columns:
            raise ValueError(f"Missing column: {col}")
    return True