# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LLvXUd1ahxq_lEzFQFvsKVMKxKcvUspy
"""

import joblib
from sklearn.metrics import classification_report, accuracy_score

def load_model(model_path):
    return joblib.load(model_path)

def predict(model, X):
    return model.predict(X)

def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    report = classification_report(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    return report, accuracy